### PR TITLE
Moving KeyRingMock class to a single file

### PR DESCRIPTION
**Pull request by sommobilitat**
Since the KeyRingMock class is the same one used in apiexample_test and packaging_test, we consider that moving the class to the packaging file is a good option, so we don't have the same class duplicated.

### CODE REVIEW

**Comment by oriolusler** [comment]
Yes, I agree with your point. We did not think with `` `pip install -e .``` and that's why we used the inits. My bad, thanks for the suggestion. I'll correct it.

**Comment by bernatixer** [comment]
About the `KeyRingMock ` we saw that it is used in the `api-example-somacme.py` file in order to parse the data, so we though it is used in the public protocol.

**Comment by vokimon** [comment]
Don't replicate my mistakes. ;-) You don't want this mockup to be your production KeyRing. Keys should be loaded on request and maybe be stored in a db.

**Comment by bernatixer** [comment]
Okey, understood. What do you think about creating a yaml file containing the location of the keys? And on the `packaging.py` we load that file in order to parse the data. And when we receive a request, we load the key.

Have you though about uploading intercoop to pip? We currently use the protocol in different projects so it would be very useful if it's in the pip database.

**Comment by vokimon** [comment]
## this PR

Implementing in some decent way the KeyRing interface would be a nice addition, but this PR is still useful by addressing the duplication issue and reuse the mock in package_test.

## About implementing production valid KeyRing

For the SomEnergia implementation we temporary implemented the KeyRing interface with a directory based implementation like the peerinfo does in the example. That implementation would be nicer for the example but since it is still an insecure approach i felt bad to include a working insecure implementation. The trend would be to skip the needed reimplementation.

Also i was thinking to include the key into the peerinfo yaml so maybe we could implement a KeyRing relaying on PeerInfo interface.

## packaging

I will eventually upload it to the pip database, it is the way to proceed. I will do that when we have a release. Meanwhile pip have many ways of properly installing it in your virtual environments. You can checkout and `pip install` the directory (with `--editable` if you want to keep the install updated with your local edits) or even install the github repo without having a clone: 

 pip install 'git+http://github.com/Som-Energia/intercoop.git#subdirectory=python'

**Comment by vokimon** [comment]
Yesterday I tried to apply the PR but i didn't apply because the merge was required. So i removed the duplication myself. The difference is that i kept the mock class in a test module, while the pr moves it to packaging module.

Notice that after the merge the resulting PR is to move the class to the packaging module which is not what we want.

I close the PR.

**Pull request closed without merging**
